version: '3.8'

services:
  # Discovery Server (Eureka)
  discovery-server:
    build: ./discoveryserver
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Users Service
  users-service:
    build: ./users
    container_name: users-service
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - chat-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Discussion Service
  discussion-service:
    build: ./discussion
    container_name: discussion-service
    ports:
      - "8083:8083"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - chat-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Feed Service
  feed-service:
    build: ./feed
    container_name: feed-service
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      users-service:
        condition: service_healthy
      discussion-service:
        condition: service_healthy
    networks:
      - chat-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      discovery-server:
        condition: service_healthy
      users-service:
        condition: service_healthy
      discussion-service:
        condition: service_healthy
      feed-service:
        condition: service_healthy
    networks:
      - chat-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge